# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile.test                                      :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: anunes-c <anunesc-@student.42barcel>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/29 23:26:37 by anunes-c          #+#    #+#              #
#    Updated: 2023/05/31 00:10:19 by anunes-c         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_printf.out
CC = cc
CFLAGS = -Wall -Wextra -Werror
AR = ar rc
SRCS = $(wildcard *.c libft/*.c)
OBJS = $(SRCS:.c=.o)
LIBFT_MAKE = $(MAKE) -C $(LIBFT_DIR)

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(OBJS) -o $(NAME)

%.o: %.c
	@$(CC) -c $< -o $@

clean:
	@rm -f $(OBJS)

fclean: clean
	@rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
